name: CI

'on':
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: cargo test --workspace

  WASM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Build WASM
        run: cargo build --target wasm32-unknown-unknown --workspace

  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate Workflows
        run: |-
          npm i
          npm run build
          npm run check-workflows

  Rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Run rustfmt
        run: cargo +nightly fmt -- --check

  Clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
